### ISSUE TITLE
Support nested, structured template data

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#47]
Needed for adding multiple SSH keys or for templates which have lists of items.

```
metadata:
  networkd
    name: ens3
    gateway: 172.15.0.1
  ssh_authorized_keys:
    - "ssh-rsa pub_key"
```
