### ISSUE TITLE
Add `selector` tags into metadata for templates

### ISSUE THREAD

**Issue by dghubble** [coreos/coreos-baremetal#64]
For a `bootcfg` top-level YAML config, it would be useful to add a group's `require` tags into the set of metadata available for Ignition configs and Cloud-configs to use so that hardware attributes don't need to be repeated as `metadata`.

```
groups:
  - name: Master Node
    spec: kubernetes-master
    require:
      uuid: c307f480-7277-11e3-8720-abcdabcdeadb
      mac: 52:da:00:89:d8:10
    metadata:
      networkd_gateway: 192.168.1.1
```

Allow templates to use `{{.uuid}}`, `{{.mac}}`, and `{{networkd_gateway}}` in templates. Currently, only `{{networkd_gateway}}` is available. Decide on a strategy for namespacing to prevent conflict with user's custom metadata.
