### ISSUE TITLE
Serve nested metadata

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#84]
When defining nested metadata like the following:
```yaml
---
api_version: v1alpha1
groups:
  - name: Worker
    spec: worker
    metadata:
      fleet:
        public_ip: ...
        metadata: ...
```

bootcfg will generate the following on requests to `/metadata`:
```sh
FLEET=map[public_ip:...]
```

I would instead expect the following:
```sh
FLEET_PUBLIC_IP=...
FLEET_METADATA=...
```
