### ISSUE TITLE
bootcfg renders integers in metadata badly

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#85]
With a config.yaml like the following:
```yaml
---
api_version: v1alpha1
groups:
  - name: Worker
    spec: worker
    metadata:
      rack: 1
```

bootcfg renders the following upon requests to `/metadata`:
```sh
RACK=%!s(int=1)
```

I would instead expect it to render:
```s
RACK=1
```

**Comment by dghubble** [comment]
Depending on the solution chosen for gRPC metadata message types, metadata may be limited to string values at the leaves. If that's the case, some validation will be used to reject configs like this. TBD

**Comment by urzds** [comment]
How would I force `1` to be a string value of "1" instead of an integer value of 1?

**Comment by dghubble** [comment]
This was addressed in some of the gRPC work.

The `bootcfg` config file will treat `metadata` more strictly in v0.3, starting at 717a240b1d5. The config.yaml may contain any valid YAML, but `bootcfg` will ignore (and log) metadata values that aren't either a string, list of strings, or nested map of strings or lists.

```
---
api_version: v1alpha1
groups:
  - name: Worker
    spec: worker
    metadata:
      rack: 1
      some_proxy: on
```

```
2016-03-11 13:20:20.268894 E | config: ignoring metadata value true
2016-03-11 13:20:20.268935 E | config: ignoring metadata value 1
2016-03-11 13:20:20.268981 I | main: starting bootcfg HTTP server on 0.0.0.0:8080
```

All metadata is serialized as JSON `[]byte` in gRPC message types so this simplifies the conversion, avoids issues where YAML "helpfully" converts `on` to `true`, and continues to allow nesting. Instead, quote strings in `metadata`.

```
---
api_version: v1alpha1
groups:
  - name: Worker
    spec: worker
    metadata:
      rack: "1"
      some_proxy: "on"
```

This may be made more lenient case by case. If YAML still proves to be troublesome, I imagine `bootcfg` should switch to require JSON top-level configs.
