### ISSUE TITLE
bootcfg ignition: storage.disks.wipeTable not rendered

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#88]
(Part of) My bootcfg ignition config:
```yaml
---
ignition_version: 1
storage:
  disks:
    - device: /dev/sda
      wipeTable: true
      partitions:
        - number: 1
          size: 0
          start: 0
```

bootcfg renders this as:
```json
{"ignitionVersion":1,"storage":{"disks":[{"device":"/dev/sda","partitions":[{"number":1,"size":0,"start":0}]}]}}
```

Observe that `wipeTable` was not rendered to JSON.

I am trying to wipe a broken GPT, which causes ignition-disks.service to not come up.
