### ISSUE TITLE
Merge spec into config?

### ISSUE THREAD

**Issue by urzds** [coreos/coreos-baremetal#96]
This is mostly regarding #36 and #92.

What about merging the spec into the config, but split the boot configuration into a separate file? The benefit would be that it would be intuitive which files are templates (everything except the config), all templates were referenced in the config using a filename and everything could be YAML.

The resulting layout and file formats would be:
```yaml
# data/config.yaml
api_version: v1alpha2
groups:
  - name: X
    ignition: x-i.yaml
    cloud: x-ci.yaml
    boot: x-b.yaml
    metadata:
      x: y
```

```yaml
# data/boot/x-b.yaml
kernel: /assets/coreos/976.0.0/coreos_production_pxe.vmlinuz
initrd:
  - /assets/coreos/976.0.0/coreos_production_pxe_image.cpio.gz
cmdline:
  "coreos.config.url": "http://bootcfg:8080/ignition?uuid=${uuid}&mac=${net0/mac:hexhyp}"
  "coreos.autologin": "",
  "coreos.first_boot": ""
```
